import { VocabularyWord } from "@/data/types";

// Mock vocabulary data
const vocabularyData: Record<string, VocabularyWord[]> = {
	// Beginner Vocabulary
	"1-1": [
		// Course 1, Lesson 1: Greetings and Introductions
		{
			id: 1,
			word: "hello",
			definition: "Used as a greeting or to begin a phone conversation",
			definitionVi: "Xin chào",
			phonetic: "/həˈloʊ/",
			example: "Hello, how are you today?",
			exampleVi: "Xin chào, bạn khỏe không?",
			wordType: "interjection",
			imageUrl: "/images/placeholder-logo.svg",
			relatedWords: ["hi", "hey", "greetings"],
			dateAdded: new Date(),
			isFavorite: true,
			notes: "This is one of the most common English greetings.",
		},
		{
			id: 2,
			word: "goodbye",
			definition: "Used when leaving or ending a conversation",
			definitionVi: "Tạm biệt",
			phonetic: "/ˌɡʊdˈbaɪ/",
			example: "I have to go now, goodbye!",
			exampleVi: "Tôi phải đi bây giờ, tạm biệt!",
			wordType: "interjection",
			imageUrl: "/images/placeholder-logo.svg",
			relatedWords: ["bye", "see you", "farewell"],
		},
		{
			id: 3,
			word: "please",
			definition: "Used as a polite way of asking for something",
			definitionVi: "Làm ơn, xin vui lòng",
			phonetic: "/pliz/",
			example: "Could I have some water, please?",
			exampleVi: "Làm ơn cho tôi xin ít nước được không?",
			wordType: "adverb",
			imageUrl: "/images/placeholder-logo.svg",
		},
		{
			id: 4,
			word: "thank you",
			definition: "Used to express gratitude",
			definitionVi: "Cảm ơn",
			phonetic: "/ˈθæŋk ju/",
			example: "Thank you for your help.",
			exampleVi: "Cảm ơn vì sự giúp đỡ của bạn.",
			wordType: "phrase",
			relatedWords: ["thanks", "grateful", "appreciate"],
		},
		{
			id: 5,
			word: "welcome",
			definition: "Used as a greeting to someone arriving",
			definitionVi: "Chào mừng",
			phonetic: "/ˈwɛlkəm/",
			example: "Welcome to our home!",
			exampleVi: "Chào mừng đến với nhà của chúng tôi!",
			wordType: "interjection",
			imageUrl: "/images/placeholder-logo.svg",
		},
		{
			id: 6,
			word: "introduce",
			definition: "To present someone by name to another person",
			definitionVi: "Giới thiệu",
			phonetic: "/ˌɪntrəˈdus/",
			example: "Let me introduce you to my friend.",
			exampleVi: "Hãy để tôi giới thiệu bạn với bạn của tôi.",
			wordType: "verb",
			relatedWords: ["presentation", "introduction"],
		},
		{
			id: 7,
			word: "name",
			definition: "A word or words by which a person is known",
			definitionVi: "Tên",
			phonetic: "/neɪm/",
			example: "My name is John.",
			exampleVi: "Tên tôi là John.",
			wordType: "noun",
			imageUrl: "/images/placeholder-logo.svg",
		},
		{
			id: 8,
			word: "meet",
			definition:
				"To come into the presence of someone for the first time",
			definitionVi: "Gặp gỡ",
			phonetic: "/mit/",
			example: "It's nice to meet you.",
			exampleVi: "Rất vui được gặp bạn.",
			wordType: "verb",
			relatedWords: ["meeting", "encounter", "introduction"],
		},
		{
			id: 9,
			word: "friend",
			definition: "A person with whom one has a bond of mutual affection",
			definitionVi: "Bạn bè",
			phonetic: "/frɛnd/",
			example: "She is my best friend.",
			exampleVi: "Cô ấy là bạn thân nhất của tôi.",
			wordType: "noun",
			imageUrl: "/images/placeholder-logo.svg",
			isFavorite: true,
		},
		{
			id: 10,
			word: "family",
			definition: "A group of people related by blood or marriage",
			definitionVi: "Gia đình",
			phonetic: "/ˈfæməli/",
			example: "I have a large family with many cousins.",
			exampleVi: "Tôi có một gia đình lớn với nhiều anh em họ.",
			wordType: "noun",
			imageUrl: "/images/placeholder-logo.svg",
			relatedWords: ["relatives", "parents", "siblings"],
		},
	],
	"1-2": [
		// Course 1, Lesson 2: Daily Activities
		{
			id: 1,
			word: "morning",
			definition: "The early part of the day",
			definitionVi: "Buổi sáng",
			phonetic: "/ˈmɔrnɪŋ/",
			example: "I always eat breakfast in the morning.",
			exampleVi: "Tôi luôn ăn sáng vào buổi sáng.",
			wordType: "noun",
			imageUrl: "/images/placeholder-logo.svg",
		},
		{
			id: 2,
			word: "afternoon",
			definition: "The time from noon until evening",
			definitionVi: "Buổi chiều",
			phonetic: "/ˌæftərˈnun/",
			example: "We have a meeting this afternoon.",
			exampleVi: "Chúng tôi có một cuộc họp vào chiều nay.",
			wordType: "noun",
			relatedWords: ["noon", "midday", "evening"],
		},
		{
			id: 3,
			word: "evening",
			definition: "The period of time at the end of the day",
			definitionVi: "Buổi tối",
			phonetic: "/ˈivnɪŋ/",
			example: "I like to read in the evening.",
			exampleVi: "Tôi thích đọc sách vào buổi tối.",
			wordType: "noun",
			imageUrl: "/images/placeholder-logo.svg",
		},
		{
			id: 4,
			word: "breakfast",
			definition: "The first meal of the day",
			definitionVi: "Bữa sáng",
			phonetic: "/ˈbrɛkfəst/",
			example: "I had eggs for breakfast.",
			exampleVi: "Tôi đã ăn trứng cho bữa sáng.",
			wordType: "noun",
			relatedWords: ["morning", "meal", "food"],
		},
		{
			id: 5,
			word: "lunch",
			definition: "A meal eaten in the middle of the day",
			definitionVi: "Bữa trưa",
			phonetic: "/lʌntʃ/",
			example: "Let's have lunch together.",
			exampleVi: "Hãy cùng nhau ăn trưa.",
			wordType: "noun",
			imageUrl: "/images/placeholder-logo.svg",
			isFavorite: true,
		},
		{
			id: 6,
			word: "dinner",
			definition: "The main meal of the day, typically in the evening",
			definitionVi: "Bữa tối",
			phonetic: "/ˈdɪnər/",
			example: "We're having pasta for dinner.",
			exampleVi: "Chúng tôi đang ăn mì Ý cho bữa tối.",
			wordType: "noun",
			relatedWords: ["supper", "evening meal", "feast"],
		},
		{
			id: 7,
			word: "work",
			definition: "Activity involving mental or physical effort",
			definitionVi: "Làm việc",
			phonetic: "/wɜrk/",
			example: "I go to work at 8 AM.",
			exampleVi: "Tôi đi làm lúc 8 giờ sáng.",
			wordType: "noun",
			imageUrl: "/images/placeholder-logo.svg",
		},
		{
			id: 8,
			word: "study",
			definition:
				"The devotion of time and attention to gaining knowledge",
			definitionVi: "Học tập",
			phonetic: "/ˈstʌdi/",
			example: "I need to study for my exam.",
			exampleVi: "Tôi cần học cho kỳ thi của mình.",
			wordType: "verb",
			relatedWords: ["learn", "education", "research"],
		},
		{
			id: 9,
			word: "sleep",
			definition:
				"A condition of body and mind in which consciousness is temporarily lost",
			definitionVi: "Ngủ",
			phonetic: "/slip/",
			example: "I usually sleep for eight hours each night.",
			exampleVi: "Tôi thường ngủ tám tiếng mỗi đêm.",
			wordType: "verb",
			imageUrl: "/images/placeholder-logo.svg",
			notes: "This word can be both a verb and a noun.",
		},
		{
			id: 10,
			word: "exercise",
			definition:
				"Activity requiring physical effort, carried out to sustain health",
			definitionVi: "Tập thể dục",
			phonetic: "/ˈɛksərˌsaɪz/",
			example: "I do exercise every morning to stay healthy.",
			exampleVi: "Tôi tập thể dục mỗi sáng để giữ gìn sức khỏe.",
			wordType: "noun",
			relatedWords: ["workout", "fitness", "training"],
			isFavorite: true,
		},
	],
	"2-1": [
		// Course 2, Lesson 1: Business English
		{
			id: 1,
			word: "meeting",
			definition: "An assembly of people for discussion or business",
			definitionVi: "Cuộc họp",
			phonetic: "/ˈmiːtɪŋ/",
			example: "We have a team meeting every Monday.",
			exampleVi: "Chúng tôi có cuộc họp nhóm vào mỗi thứ Hai.",
			wordType: "noun",
			imageUrl: "/images/placeholder-logo.svg",
			relatedWords: ["conference", "discussion", "gathering"],
		},
		{
			id: 2,
			word: "deadline",
			definition:
				"The latest time by which something should be completed",
			definitionVi: "Thời hạn chót",
			phonetic: "/ˈdɛdˌlaɪn/",
			example: "The deadline for this project is Friday.",
			exampleVi: "Thời hạn chót cho dự án này là thứ Sáu.",
			wordType: "noun",
			isFavorite: true,
		},
		{
			id: 3,
			word: "negotiate",
			definition: "To discuss with a view to finding an agreement",
			definitionVi: "Đàm phán",
			phonetic: "/nɪˈɡoʊʃiˌeɪt/",
			example: "We need to negotiate the terms of the contract.",
			exampleVi: "Chúng ta cần đàm phán các điều khoản của hợp đồng.",
			wordType: "verb",
			relatedWords: ["bargain", "discuss", "compromise"],
		},
		{
			id: 4,
			word: "budget",
			definition:
				"An estimate of income and expenditure for a set period",
			definitionVi: "Ngân sách",
			phonetic: "/ˈbʌdʒɪt/",
			example: "The budget for this quarter is very tight.",
			exampleVi: "Ngân sách cho quý này rất hạn hẹp.",
			wordType: "noun",
			imageUrl: "/images/placeholder-logo.svg",
		},
		{
			id: 5,
			word: "client",
			definition: "A person who receives professional services",
			definitionVi: "Khách hàng",
			phonetic: "/ˈklaɪənt/",
			example: "Our client was very satisfied with our work.",
			exampleVi:
				"Khách hàng của chúng tôi rất hài lòng với công việc của chúng tôi.",
			wordType: "noun",
			relatedWords: ["customer", "patron", "consumer"],
		},
		{
			id: 6,
			word: "proposal",
			definition: "A plan or suggestion put forward for consideration",
			definitionVi: "Đề xuất",
			phonetic: "/prəˈpoʊzəl/",
			example: "I submitted my proposal to the board yesterday.",
			exampleVi:
				"Tôi đã gửi đề xuất của mình cho hội đồng quản trị hôm qua.",
			wordType: "noun",
			imageUrl: "/images/placeholder-logo.svg",
			notes: "In business contexts, a proposal is often a formal document.",
		},
		{
			id: 7,
			word: "schedule",
			definition: "A plan for carrying out a process or procedure",
			definitionVi: "Lịch trình",
			phonetic: "/ˈskɛdʒuːl/",
			example: "Let's check the schedule for next week.",
			exampleVi: "Hãy kiểm tra lịch trình cho tuần tới.",
			wordType: "noun",
			relatedWords: ["timetable", "agenda", "plan"],
		},
		{
			id: 8,
			word: "collaborate",
			definition: "To work jointly on an activity or project",
			definitionVi: "Hợp tác",
			phonetic: "/kəˈlæbəˌreɪt/",
			example: "Our teams will collaborate on this initiative.",
			exampleVi: "Các đội của chúng tôi sẽ hợp tác trong sáng kiến này.",
			wordType: "verb",
			imageUrl: "/images/placeholder-logo.svg",
			isFavorite: true,
		},
		{
			id: 9,
			word: "strategy",
			definition: "A plan of action designed to achieve a long-term goal",
			definitionVi: "Chiến lược",
			phonetic: "/ˈstrætədʒi/",
			example: "We need to develop a new marketing strategy.",
			exampleVi: "Chúng ta cần phát triển một chiến lược tiếp thị mới.",
			wordType: "noun",
			relatedWords: ["plan", "approach", "tactic"],
		},
		{
			id: 10,
			word: "presentation",
			definition:
				"A speech or talk in which a new product, idea, or piece of work is shown",
			definitionVi: "Bài thuyết trình",
			phonetic: "/ˌprɛzənˈteɪʃən/",
			example: "I'm preparing a presentation for tomorrow's meeting.",
			exampleVi:
				"Tôi đang chuẩn bị một bài thuyết trình cho cuộc họp ngày mai.",
			wordType: "noun",
			imageUrl: "/images/placeholder-logo.svg",
		},
	],
	"2-2": [
		// Course 2, Lesson 2: Travel and Transportation
		{
			id: 1,
			word: "airport",
			definition:
				"A complex of runways and buildings for the takeoff, landing, and maintenance of aircraft",
			definitionVi: "Sân bay",
			phonetic: "/ˈɛrˌpɔrt/",
			example: "We arrived at the airport two hours before our flight.",
			exampleVi: "Chúng tôi đã đến sân bay hai giờ trước chuyến bay.",
			wordType: "noun",
			imageUrl: "/images/placeholder-logo.svg",
		},
		{
			id: 2,
			word: "passport",
			definition:
				"An official document issued by a government, certifying the holder's identity and citizenship",
			definitionVi: "Hộ chiếu",
			phonetic: "/ˈpæsˌpɔrt/",
			example:
				"Don't forget to bring your passport when traveling internationally.",
			exampleVi: "Đừng quên mang theo hộ chiếu khi đi du lịch quốc tế.",
			wordType: "noun",
			relatedWords: ["identification", "travel document", "visa"],
			isFavorite: true,
		},
		{
			id: 3,
			word: "ticket",
			definition:
				"A piece of paper or small card that gives the holder a certain right, especially to enter a place, travel by public transport, or participate in an event",
			definitionVi: "Vé",
			phonetic: "/ˈtɪkɪt/",
			example: "I bought a train ticket to Paris.",
			exampleVi: "Tôi đã mua một vé tàu đi Paris.",
			wordType: "noun",
			imageUrl: "/images/placeholder-logo.svg",
		},
		{
			id: 4,
			word: "baggage",
			definition: "The luggage carried by a traveler",
			definitionVi: "Hành lý",
			phonetic: "/ˈbæɡɪdʒ/",
			example: "We checked our baggage at the counter.",
			exampleVi: "Chúng tôi đã gửi hành lý tại quầy.",
			wordType: "noun",
			relatedWords: ["luggage", "suitcase", "belongings"],
		},
		{
			id: 5,
			word: "reservation",
			definition:
				"An arrangement to have something (such as a seat on a plane) held for one's use",
			definitionVi: "Đặt chỗ",
			phonetic: "/ˌrɛzərˈveɪʃən/",
			example: "I made a reservation at the hotel.",
			exampleVi: "Tôi đã đặt chỗ tại khách sạn.",
			wordType: "noun",
			imageUrl: "/images/placeholder-logo.svg",
		},
		{
			id: 6,
			word: "destination",
			definition:
				"The place to which someone or something is going or being sent",
			definitionVi: "Điểm đến",
			phonetic: "/ˌdɛstəˈneɪʃən/",
			example: "Our destination is New York City.",
			exampleVi: "Điểm đến của chúng tôi là thành phố New York.",
			wordType: "noun",
			relatedWords: ["goal", "target", "end point"],
		},
		{
			id: 7,
			word: "transportation",
			definition:
				"The action of transporting someone or something or the process of being transported",
			definitionVi: "Vận chuyển",
			phonetic: "/ˌtrænspərˈteɪʃən/",
			example: "Public transportation is very convenient in this city.",
			exampleVi:
				"Giao thông công cộng rất thuận tiện trong thành phố này.",
			wordType: "noun",
			imageUrl: "/images/placeholder-logo.svg",
		},
		{
			id: 8,
			word: "luggage",
			definition:
				"Suitcases or other bags in which to pack personal belongings for traveling",
			definitionVi: "Hành lý",
			phonetic: "/ˈlʌɡɪdʒ/",
			example: "I packed my luggage for the trip.",
			exampleVi: "Tôi đã đóng gói hành lý cho chuyến đi.",
			wordType: "noun",
			relatedWords: ["baggage", "suitcase", "bags"],
		},
		{
			id: 9,
			word: "itinerary",
			definition: "A planned route or journey",
			definitionVi: "Lịch trình",
			phonetic: "/aɪˈtɪnəˌrɛri/",
			example: "Our itinerary includes visits to several museums.",
			exampleVi:
				"Lịch trình của chúng tôi bao gồm các chuyến thăm đến một số bảo tàng.",
			wordType: "noun",
			imageUrl: "/images/placeholder-logo.svg",
		},
		{
			id: 10,
			word: "accommodation",
			definition:
				"A room, group of rooms, or building in which someone may live or stay",
			definitionVi: "Chỗ ở",
			phonetic: "/əˌkɑməˈdeɪʃən/",
			example: "We found a nice accommodation for our vacation.",
			exampleVi:
				"Chúng tôi đã tìm thấy một chỗ ở tốt cho kỳ nghỉ của mình.",
			wordType: "noun",
			relatedWords: ["lodging", "housing", "residence"],
		},
	],
};

export function getVocabularyWords(
	courseId: number,
	lessonId: number
): VocabularyWord[] {
	const key = `${courseId}-${lessonId}`;

	// Return the vocabulary words for the specified course and lesson
	// If not found, return a default set
	return (
		vocabularyData[key] || [
			{
				id: 1,
				word: "example",
				definition:
					"A thing characteristic of its kind or illustrating a general rule",
				definitionVi:
					"Một vật đặc trưng cho loại của nó hoặc minh họa cho một quy tắc chung",
				phonetic: "/ɪɡˈzɑːmpəl/",
				example: "This is an example of a vocabulary word.",
				exampleVi: "Đây là một ví dụ về từ vựng.",
				wordType: "noun",
				imageUrl: "/images/placeholder-logo.svg",
				dateAdded: new Date(),
			},
			{
				id: 2,
				word: "vocabulary",
				definition: "The body of words used in a particular language",
				definitionVi:
					"Toàn bộ từ ngữ được sử dụng trong một ngôn ngữ cụ thể",
				phonetic: "/vəˈkæbjəˌlɛri/",
				example:
					"Learning vocabulary is essential for language acquisition.",
				exampleVi:
					"Học từ vựng là điều cần thiết để tiếp thu ngôn ngữ.",
				wordType: "noun",
				imageUrl: "/images/placeholder-logo.svg",
				relatedWords: ["word", "lexicon", "terminology"],
			},
			{
				id: 3,
				word: "practice",
				definition:
					"The actual application or use of an idea, belief, or method",
				definitionVi:
					"Ứng dụng hoặc sử dụng thực tế một ý tưởng, niềm tin hoặc phương pháp",
				phonetic: "/ˈpræktɪs/",
				example: "Practice makes perfect.",
				exampleVi: "Thực hành tạo nên sự hoàn hảo.",
				wordType: "noun",
				imageUrl: "/images/placeholder-logo.svg",
				isFavorite: true,
			},
			{
				id: 4,
				word: "learn",
				definition:
					"Gain or acquire knowledge of or skill in by study, experience, or being taught",
				definitionVi:
					"Đạt được hoặc tiếp thu kiến thức hay kỹ năng thông qua học tập, kinh nghiệm hoặc được dạy",
				phonetic: "/lɜrn/",
				example: "I want to learn English.",
				exampleVi: "Tôi muốn học tiếng Anh.",
				wordType: "verb",
				relatedWords: ["study", "acquire", "master"],
			},
			{
				id: 5,
				word: "language",
				definition:
					"The method of human communication, either spoken or written",
				definitionVi:
					"Phương thức giao tiếp của con người, bằng lời nói hoặc chữ viết",
				phonetic: "/ˈlæŋɡwɪdʒ/",
				example: "English is a global language.",
				exampleVi: "Tiếng Anh là một ngôn ngữ toàn cầu.",
				wordType: "noun",
				imageUrl: "/images/placeholder-logo.svg",
				notes: "There are approximately 7,000 languages spoken in the world today.",
			},
			{
				id: 6,
				word: "study",
				definition:
					"The devotion of time and attention to acquiring knowledge",
				definitionVi:
					"Dành thời gian và sự chú ý để tiếp thu kiến thức",
				phonetic: "/ˈstʌdi/",
				example: "I study for two hours every day.",
				exampleVi: "Tôi học hai giờ mỗi ngày.",
				wordType: "verb",
				imageUrl: "/images/placeholder-logo.svg",
				relatedWords: ["learn", "research", "investigate"],
			},
			{
				id: 7,
				word: "word",
				definition:
					"A single distinct meaningful element of speech or writing",
				definitionVi:
					"Một thành phần riêng biệt có ý nghĩa trong lời nói hoặc chữ viết",
				phonetic: "/wɜrd/",
				example: "This sentence has seven words.",
				exampleVi: "Câu này có bảy từ.",
				wordType: "noun",
				imageUrl: "/images/placeholder-logo.svg",
				dateAdded: new Date(),
			},
			{
				id: 8,
				word: "sentence",
				definition: "A set of words that is complete in itself",
				definitionVi: "Một tập hợp các từ hoàn chỉnh",
				phonetic: "/ˈsɛntəns/",
				example: "Can you write a complete sentence?",
				exampleVi: "Bạn có thể viết một câu hoàn chỉnh không?",
				wordType: "noun",
				relatedWords: ["phrase", "clause", "statement"],
				isFavorite: true,
			},
			{
				id: 9,
				word: "meaning",
				definition: "What is meant by a word, text, concept, or action",
				definitionVi:
					"Ý nghĩa của một từ, văn bản, khái niệm hoặc hành động",
				phonetic: "/ˈminɪŋ/",
				example: "Do you know the meaning of this word?",
				exampleVi: "Bạn có biết ý nghĩa của từ này không?",
				wordType: "noun",
				imageUrl: "/images/placeholder-logo.svg",
			},
			{
				id: 10,
				word: "pronunciation",
				definition: "The way in which a word is pronounced",
				definitionVi: "Cách phát âm một từ",
				phonetic: "/prəˌnʌnsiˈeɪʃən/",
				example: "English pronunciation can be difficult.",
				exampleVi: "Phát âm tiếng Anh có thể khó khăn.",
				wordType: "noun",
				imageUrl: "/images/placeholder-logo.svg",
				relatedWords: ["accent", "articulation", "enunciation"],
				notes: "Practicing pronunciation regularly will improve your speaking skills.",
			},
		]
	);
}
